apiVersion: v1
data:
  accessKeyId: TUlTU0lORw==
kind: Secret
metadata:
  labels:
    app: signalsciences-signalsciences
    chart: signalsciences-0.0.1
    heritage: Tiller
    release: signalsciences
  name: signalsciences-signalsciences-accesskeyid
type: Opaque
---
apiVersion: v1
data:
  secretAccessKey: TUlTU0lORw==
kind: Secret
metadata:
  labels:
    app: signalsciences-signalsciences
    chart: signalsciences-0.0.1
    heritage: Tiller
    release: signalsciences
  name: signalsciences-signalsciences-secretaccesskey
type: Opaque
